<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="fhir-ig-uscore-dotnet" Version="1.0.3" />
    <PackageReference Include="Hangfire" Version="1.8.12" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.12" />
    <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.1" />
    <PackageReference Include="Hl7.Fhir.R4" Version="5.11.1" />
    <PackageReference Include="Hl7.FhirPath" Version="4.3.0" />
    <PackageReference Include="IdentityServer4" Version="4.1.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.35.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.35.0" />
    <PackageReference Include="RestSharp" Version="110.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Interface.Models\Interface.Models.csproj" />
  </ItemGroup>

</Project>
